-- MySQL Script generated by MySQL Workbench
-- Mon Jun 24 15:01:38 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `Biblioteca` ;

-- -----------------------------------------------------
-- Table `Biblioteca`.`Editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Editora` (
  `idEditora` INT NOT NULL,
  `Editora_nome` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`idEditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Autor` (
  `idAutor` INT NOT NULL,
  `nome_do_autor` VARCHAR(45) NOT NULL,
  `nacionalidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Livro` (
  `idLivro` INT NOT NULL,
  `Editora_idEditora` INT NOT NULL,
  `Autor_idAutor` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `isbn` DOUBLE NOT NULL,
  `ano_publicacao` DOUBLE NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLivro`),
  INDEX `fk_Livro_Editora1_idx` (`Editora_idEditora` ASC),
  INDEX `fk_Livro_Autor1_idx` (`Autor_idAutor` ASC),
  CONSTRAINT `fk_Livro_Editora1`
    FOREIGN KEY (`Editora_idEditora`)
    REFERENCES `Biblioteca`.`Editora` (`idEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_Autor1`
    FOREIGN KEY (`Autor_idAutor`)
    REFERENCES `Biblioteca`.`Autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Emprestimo` (
  `idEmprestimo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Livro_idLivro` INT NOT NULL,
  `dataEmprestimo` INT NOT NULL,
  `dataDevolucao` INT NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  INDEX `fk_Emprestimo_Usuario1_idx` (`Usuario_idUsuario` ASC),
  PRIMARY KEY (`idEmprestimo`),
  INDEX `fk_Emprestimo_Livro1_idx` (`Livro_idLivro` ASC),
  CONSTRAINT `fk_Emprestimo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `Biblioteca`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Emprestimo_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `Biblioteca`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Biblioteca`.`Livro_has_Emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biblioteca`.`Livro_has_Emprestimo` (
  `Livro_idLivro` INT NOT NULL,
  `Emprestimo_idEmprestimo` INT NOT NULL,
  INDEX `fk_Livro_has_Emprestimo_Emprestimo1_idx` (`Emprestimo_idEmprestimo` ASC),
  INDEX `fk_Livro_has_Emprestimo_Livro1_idx` (`Livro_idLivro` ASC),
  PRIMARY KEY (`Livro_idLivro`, `Emprestimo_idEmprestimo`),
  CONSTRAINT `fk_Livro_has_Emprestimo_Livro1`
    FOREIGN KEY (`Livro_idLivro`)
    REFERENCES `Biblioteca`.`Livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Livro_has_Emprestimo_Emprestimo1`
    FOREIGN KEY (`Emprestimo_idEmprestimo`)
    REFERENCES `Biblioteca`.`Emprestimo` (`idEmprestimo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;